//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{
    public static class ConnectionHelper
    {
        static Type[] persistentTypes = new Type[] {
            typeof(Alphabeticallistofproducts),
            typeof(Categories),
            typeof(CategorySalesfor1997),
            typeof(CurrentProductList),
            typeof(CustomerandSuppliersbyCity),
            typeof(CustomerCustomerDemo),
            typeof(CustomerDemographics),
            typeof(Customers),
            typeof(Employees),
            typeof(EmployeeTerritories),
            typeof(Invoices),
            typeof(LogEntries),
            typeof(OrderDetails),
            typeof(OrderDetailsExtended),
            typeof(OrderSubtotals),
            typeof(Orders),
            typeof(OrdersQry),
            typeof(ProductSalesfor1997),
            typeof(Products),
            typeof(ProductsAboveAveragePrice),
            typeof(ProductsbyCategory),
            typeof(QuarterlyOrders),
            typeof(Region),
            typeof(SalesbyCategory),
            typeof(SalesTotalsbyAmount),
            typeof(Shippers),
            typeof(SummaryofSalesbyQuarter),
            typeof(SummaryofSalesbyYear),
            typeof(Suppliers),
            typeof(sysdiagrams),
            typeof(Territories)
        };
        public static Type[] GetPersistentTypes()
        {
            Type[] copy = new Type[persistentTypes.Length];
            Array.Copy(persistentTypes, copy, persistentTypes.Length);
            return copy;
        }
        public const string ConnectionString = @"XpoProvider=MSSqlServer;data source=localhost\MSSQLSERVER2014;integrated security=SSPI;initial catalog=Northwind";
        public static void Connect(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, bool threadSafe = false)
        {
            if (threadSafe)
            {
                var provider = XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
                var dictionary = new DevExpress.Xpo.Metadata.ReflectionDictionary();
                dictionary.GetDataStoreSchema(persistentTypes);
                XpoDefault.DataLayer = new ThreadSafeDataLayer(dictionary, provider);
            }
            else
            {
                XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
            }
            XpoDefault.Session = null;
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption);
        }
        public static DevExpress.Xpo.DB.IDataStore GetConnectionProvider(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption, out IDisposable[] objectsToDisposeOnDisconnect)
        {
            return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, out objectsToDisposeOnDisconnect);
        }
        public static IDataLayer GetDataLayer(DevExpress.Xpo.DB.AutoCreateOption autoCreateOption)
        {
            return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption);
        }
    }

}
