//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class CustomerCustomerDemo : XPLiteObject
    {
        public struct CompoundKey1Struct
        {
            [Size(5)]
            [Persistent("CustomerID")]
            public string CustomerID { get; set; }
            [Size(10)]
            [Persistent("CustomerTypeID")]
            public string CustomerTypeID { get; set; }
        }
        [Key, Persistent]
        public CompoundKey1Struct CompoundKey1;
    }

}
