//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class Employees : XPLiteObject
    {
        int fEmployeeID;
        [Key(true)]
        public int EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<int>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        string fLastName;
        [Indexed(Name = @"LastName")]
        [Size(20)]
        public string LastName
        {
            get { return fLastName; }
            set { SetPropertyValue<string>(nameof(LastName), ref fLastName, value); }
        }
        string fFirstName;
        [Size(10)]
        public string FirstName
        {
            get { return fFirstName; }
            set { SetPropertyValue<string>(nameof(FirstName), ref fFirstName, value); }
        }
        string fTitle;
        [Size(30)]
        public string Title
        {
            get { return fTitle; }
            set { SetPropertyValue<string>(nameof(Title), ref fTitle, value); }
        }
        string fTitleOfCourtesy;
        [Size(25)]
        public string TitleOfCourtesy
        {
            get { return fTitleOfCourtesy; }
            set { SetPropertyValue<string>(nameof(TitleOfCourtesy), ref fTitleOfCourtesy, value); }
        }
        DateTime fBirthDate;
        public DateTime BirthDate
        {
            get { return fBirthDate; }
            set { SetPropertyValue<DateTime>(nameof(BirthDate), ref fBirthDate, value); }
        }
        DateTime fHireDate;
        public DateTime HireDate
        {
            get { return fHireDate; }
            set { SetPropertyValue<DateTime>(nameof(HireDate), ref fHireDate, value); }
        }
        string fAddress;
        [Size(60)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCity;
        [Size(15)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fRegion;
        [Size(15)]
        public string Region
        {
            get { return fRegion; }
            set { SetPropertyValue<string>(nameof(Region), ref fRegion, value); }
        }
        string fPostalCode;
        [Indexed(Name = @"PostalCode")]
        [Size(10)]
        public string PostalCode
        {
            get { return fPostalCode; }
            set { SetPropertyValue<string>(nameof(PostalCode), ref fPostalCode, value); }
        }
        string fCountry;
        [Size(15)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        string fHomePhone;
        [Size(24)]
        public string HomePhone
        {
            get { return fHomePhone; }
            set { SetPropertyValue<string>(nameof(HomePhone), ref fHomePhone, value); }
        }
        string fExtension;
        [Size(4)]
        public string Extension
        {
            get { return fExtension; }
            set { SetPropertyValue<string>(nameof(Extension), ref fExtension, value); }
        }
        byte[] fPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<byte[]>(nameof(Photo), ref fPhoto, value); }
        }
        string fNotes;
        [Size(SizeAttribute.Unlimited)]
        public string Notes
        {
            get { return fNotes; }
            set { SetPropertyValue<string>(nameof(Notes), ref fNotes, value); }
        }
        Employees fReportsTo;
        [Association(@"EmployeesReferencesEmployees")]
        public Employees ReportsTo
        {
            get { return fReportsTo; }
            set { SetPropertyValue<Employees>(nameof(ReportsTo), ref fReportsTo, value); }
        }
        string fPhotoPath;
        [Size(255)]
        public string PhotoPath
        {
            get { return fPhotoPath; }
            set { SetPropertyValue<string>(nameof(PhotoPath), ref fPhotoPath, value); }
        }
        [Association(@"EmployeesReferencesEmployees")]
        public XPCollection<Employees> EmployeesCollection { get { return GetCollection<Employees>(nameof(EmployeesCollection)); } }
        [Association(@"OrdersReferencesEmployees")]
        public XPCollection<Orders> OrdersCollection { get { return GetCollection<Orders>(nameof(OrdersCollection)); } }
    }

}
