//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class LogEntries : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>(nameof(ID), ref fID, value); }
        }
        int fModuleID;
        public int ModuleID
        {
            get { return fModuleID; }
            set { SetPropertyValue<int>(nameof(ModuleID), ref fModuleID, value); }
        }
        string fRecordFriendlyName;
        [Size(200)]
        public string RecordFriendlyName
        {
            get { return fRecordFriendlyName; }
            set { SetPropertyValue<string>(nameof(RecordFriendlyName), ref fRecordFriendlyName, value); }
        }
        int fRecordID;
        public int RecordID
        {
            get { return fRecordID; }
            set { SetPropertyValue<int>(nameof(RecordID), ref fRecordID, value); }
        }
        Guid fSessionID;
        public Guid SessionID
        {
            get { return fSessionID; }
            set { SetPropertyValue<Guid>(nameof(SessionID), ref fSessionID, value); }
        }
        int fUserID;
        public int UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<int>(nameof(UserID), ref fUserID, value); }
        }
        string fUserName;
        [Size(50)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>(nameof(UserName), ref fUserName, value); }
        }
        string fNameOfUser;
        [Size(50)]
        public string NameOfUser
        {
            get { return fNameOfUser; }
            set { SetPropertyValue<string>(nameof(NameOfUser), ref fNameOfUser, value); }
        }
        DateTime fDate;
        public DateTime Date
        {
            get { return fDate; }
            set { SetPropertyValue<DateTime>(nameof(Date), ref fDate, value); }
        }
        int fActionType;
        public int ActionType
        {
            get { return fActionType; }
            set { SetPropertyValue<int>(nameof(ActionType), ref fActionType, value); }
        }
        string fDetails;
        [Size(SizeAttribute.Unlimited)]
        public string Details
        {
            get { return fDetails; }
            set { SetPropertyValue<string>(nameof(Details), ref fDetails, value); }
        }
        short fClassType;
        public short ClassType
        {
            get { return fClassType; }
            set { SetPropertyValue<short>(nameof(ClassType), ref fClassType, value); }
        }
        int fActionSubTypes;
        public int ActionSubTypes
        {
            get { return fActionSubTypes; }
            set { SetPropertyValue<int>(nameof(ActionSubTypes), ref fActionSubTypes, value); }
        }
        string fIPAddress;
        [Size(50)]
        public string IPAddress
        {
            get { return fIPAddress; }
            set { SetPropertyValue<string>(nameof(IPAddress), ref fIPAddress, value); }
        }
    }

}
