//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class OrdersQry : XPLiteObject
    {
        int fOrderID;
        public int OrderID
        {
            get { return fOrderID; }
            set { SetPropertyValue<int>(nameof(OrderID), ref fOrderID, value); }
        }
        string fCustomerID;
        [Size(5)]
        public string CustomerID
        {
            get { return fCustomerID; }
            set { SetPropertyValue<string>(nameof(CustomerID), ref fCustomerID, value); }
        }
        int fEmployeeID;
        public int EmployeeID
        {
            get { return fEmployeeID; }
            set { SetPropertyValue<int>(nameof(EmployeeID), ref fEmployeeID, value); }
        }
        DateTime fOrderDate;
        public DateTime OrderDate
        {
            get { return fOrderDate; }
            set { SetPropertyValue<DateTime>(nameof(OrderDate), ref fOrderDate, value); }
        }
        DateTime fRequiredDate;
        public DateTime RequiredDate
        {
            get { return fRequiredDate; }
            set { SetPropertyValue<DateTime>(nameof(RequiredDate), ref fRequiredDate, value); }
        }
        DateTime fShippedDate;
        public DateTime ShippedDate
        {
            get { return fShippedDate; }
            set { SetPropertyValue<DateTime>(nameof(ShippedDate), ref fShippedDate, value); }
        }
        int fShipVia;
        public int ShipVia
        {
            get { return fShipVia; }
            set { SetPropertyValue<int>(nameof(ShipVia), ref fShipVia, value); }
        }
        decimal fFreight;
        public decimal Freight
        {
            get { return fFreight; }
            set { SetPropertyValue<decimal>(nameof(Freight), ref fFreight, value); }
        }
        string fShipName;
        [Size(40)]
        public string ShipName
        {
            get { return fShipName; }
            set { SetPropertyValue<string>(nameof(ShipName), ref fShipName, value); }
        }
        string fShipAddress;
        [Size(60)]
        public string ShipAddress
        {
            get { return fShipAddress; }
            set { SetPropertyValue<string>(nameof(ShipAddress), ref fShipAddress, value); }
        }
        string fShipCity;
        [Size(15)]
        public string ShipCity
        {
            get { return fShipCity; }
            set { SetPropertyValue<string>(nameof(ShipCity), ref fShipCity, value); }
        }
        string fShipRegion;
        [Size(15)]
        public string ShipRegion
        {
            get { return fShipRegion; }
            set { SetPropertyValue<string>(nameof(ShipRegion), ref fShipRegion, value); }
        }
        string fShipPostalCode;
        [Size(10)]
        public string ShipPostalCode
        {
            get { return fShipPostalCode; }
            set { SetPropertyValue<string>(nameof(ShipPostalCode), ref fShipPostalCode, value); }
        }
        string fShipCountry;
        [Size(15)]
        public string ShipCountry
        {
            get { return fShipCountry; }
            set { SetPropertyValue<string>(nameof(ShipCountry), ref fShipCountry, value); }
        }
        string fCompanyName;
        [Size(40)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>(nameof(CompanyName), ref fCompanyName, value); }
        }
        string fAddress;
        [Size(60)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fCity;
        [Size(15)]
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fRegion;
        [Size(15)]
        public string Region
        {
            get { return fRegion; }
            set { SetPropertyValue<string>(nameof(Region), ref fRegion, value); }
        }
        string fPostalCode;
        [Size(10)]
        public string PostalCode
        {
            get { return fPostalCode; }
            set { SetPropertyValue<string>(nameof(PostalCode), ref fPostalCode, value); }
        }
        string fCountry;
        [Size(15)]
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
    }

}
