//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.Persistent.Validation;

namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class Products : XPLiteObject
    {
        int fProductID;
        [Key(true)]
        public int ProductID
        {
            get { return fProductID; }
            set { SetPropertyValue<int>(nameof(ProductID), ref fProductID, value); }
        }
        string fProductName;
        [Indexed(Name = @"ProductName")]
        [Size(40)]
        [RuleRequiredField("RuleRequiredField for ProductName",DefaultContexts.Save,"A title must be specified")]
        public string ProductName
        {
            get { return fProductName; }
            set { SetPropertyValue<string>(nameof(ProductName), ref fProductName, value); }
        }
        Suppliers fSupplierID;
        [Association(@"ProductsReferencesSuppliers")]
        [RuleRequiredField("RuleRequiredField for SupplierID",DefaultContexts.Save, "Supplier must be specified")]
        public Suppliers SupplierID
        {
            get { return fSupplierID; }
            set { SetPropertyValue<Suppliers>(nameof(SupplierID), ref fSupplierID, value); }
        }
        Categories fCategoryID;
        [Association(@"ProductsReferencesCategories")]
        [RuleRequiredField("RuleRequiredField for CategoryID",DefaultContexts.Save, "Category must be specified")]
        public Categories CategoryID
        {
            get { return fCategoryID; }
            set { SetPropertyValue<Categories>(nameof(CategoryID), ref fCategoryID, value); }
        }
        string fQuantityPerUnit;
        [Size(20)]
        public string QuantityPerUnit
        {
            get { return fQuantityPerUnit; }
            set { SetPropertyValue<string>(nameof(QuantityPerUnit), ref fQuantityPerUnit, value); }
        }
        decimal fUnitPrice;
        [ColumnDbDefaultValue("(0)")]
        public decimal UnitPrice
        {
            get { return fUnitPrice; }
            set { SetPropertyValue<decimal>(nameof(UnitPrice), ref fUnitPrice, value); }
        }
        short fUnitsInStock;
        [ColumnDbDefaultValue("(0)")]
        public short UnitsInStock
        {
            get { return fUnitsInStock; }
            set { SetPropertyValue<short>(nameof(UnitsInStock), ref fUnitsInStock, value); }
        }
        short fUnitsOnOrder;
        [ColumnDbDefaultValue("(0)")]
        public short UnitsOnOrder
        {
            get { return fUnitsOnOrder; }
            set { SetPropertyValue<short>(nameof(UnitsOnOrder), ref fUnitsOnOrder, value); }
        }
        short fReorderLevel;
        [ColumnDbDefaultValue("(0)")]
        public short ReorderLevel
        {
            get { return fReorderLevel; }
            set { SetPropertyValue<short>(nameof(ReorderLevel), ref fReorderLevel, value); }
        }
        bool fDiscontinued;
        [ColumnDbDefaultValue("(0)")]
        public bool Discontinued
        {
            get { return fDiscontinued; }
            set { SetPropertyValue<bool>(nameof(Discontinued), ref fDiscontinued, value); }
        }
    }

}
