//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class Region : XPLiteObject
    {
        int fRegionID;
        [Key]
        public int RegionID
        {
            get { return fRegionID; }
            set { SetPropertyValue<int>(nameof(RegionID), ref fRegionID, value); }
        }
        string fRegionDescription;
        [Size(50)]
        public string RegionDescription
        {
            get { return fRegionDescription; }
            set { SetPropertyValue<string>(nameof(RegionDescription), ref fRegionDescription, value); }
        }
        [Association(@"TerritoriesReferencesRegion")]
        public XPCollection<Territories> TerritoriesCollection { get { return GetCollection<Territories>(nameof(TerritoriesCollection)); } }
    }

}
