//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class Shippers : XPLiteObject
    {
        int fShipperID;
        [Key(true)]
        public int ShipperID
        {
            get { return fShipperID; }
            set { SetPropertyValue<int>(nameof(ShipperID), ref fShipperID, value); }
        }
        string fCompanyName;
        [Size(40)]
        public string CompanyName
        {
            get { return fCompanyName; }
            set { SetPropertyValue<string>(nameof(CompanyName), ref fCompanyName, value); }
        }
        string fPhone;
        [Size(24)]
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        [Association(@"OrdersReferencesShippers")]
        public XPCollection<Orders> OrdersCollection { get { return GetCollection<Orders>(nameof(OrdersCollection)); } }
    }

}
