//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    [NonPersistent]
    public partial class SummaryofSalesbyYear : XPLiteObject
    {
        DateTime fShippedDate;
        public DateTime ShippedDate
        {
            get { return fShippedDate; }
            set { SetPropertyValue<DateTime>(nameof(ShippedDate), ref fShippedDate, value); }
        }
        int fOrderID;
        public int OrderID
        {
            get { return fOrderID; }
            set { SetPropertyValue<int>(nameof(OrderID), ref fOrderID, value); }
        }
        decimal fSubtotal;
        public decimal Subtotal
        {
            get { return fSubtotal; }
            set { SetPropertyValue<decimal>(nameof(Subtotal), ref fSubtotal, value); }
        }
    }

}
