//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Northwind.Module.BusinessObjects.Northwind
{

    public partial class Territories : XPLiteObject
    {
        string fTerritoryID;
        [Key]
        [Size(20)]
        public string TerritoryID
        {
            get { return fTerritoryID; }
            set { SetPropertyValue<string>(nameof(TerritoryID), ref fTerritoryID, value); }
        }
        string fTerritoryDescription;
        [Size(50)]
        public string TerritoryDescription
        {
            get { return fTerritoryDescription; }
            set { SetPropertyValue<string>(nameof(TerritoryDescription), ref fTerritoryDescription, value); }
        }
        Region fRegionID;
        [Association(@"TerritoriesReferencesRegion")]
        public Region RegionID
        {
            get { return fRegionID; }
            set { SetPropertyValue<Region>(nameof(RegionID), ref fRegionID, value); }
        }
    }

}
